const LOGIN_FETCH = 'LOGIN_FETCH';
const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
const REGISTER_FETCH = 'REGISTER_FETCH';
const REGISTER_RESPONSE = 'REGISTER_RESPONSE';
const GET_HACB_NO_FETCH = 'GET_HACB_NO_FETCH';
const GET_HACB_NO_RESPONSE = 'GET_HACB_NO_RESPONSE';
const GET_DETAIL_CNOTE_FETCH = 'GET_DETAIL_CNOTE_FETCH';
const GET_DETAIL_CNOTE_RESPONSE = 'GET_DETAIL_CNOTE_RESPONSE';

const LOADING = 'LOADING';

export default {
  LOGIN_FETCH,
  LOGIN_RESPONSE,
  REGISTER_FETCH,
  REGISTER_RESPONSE,
  GET_HACB_NO_FETCH,
  GET_HACB_NO_RESPONSE,
  GET_DETAIL_CNOTE_FETCH,
  GET_DETAIL_CNOTE_RESPONSE,
  LOADING,
};
